"""Initial durable Vigilon schema."""
from alembic import op
import sqlalchemy as sa
revision="0001_initial";down_revision=None;branch_labels=None;depends_on=None
role=sa.Enum("ADMIN","OPERATOR",name="role")
incident_status=sa.Enum("NEW","ACKNOWLEDGED","RESOLVED","FALSE_ALARM",name="incidentstatus")
def upgrade():
    op.create_table("users",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("username",sa.String(80),nullable=False,unique=True),sa.Column("password_hash",sa.String(300),nullable=False),sa.Column("role",role,nullable=False),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table("cameras",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("name",sa.String(120),nullable=False),sa.Column("location",sa.String(160),nullable=False,server_default=""),sa.Column("source_type",sa.String(20),nullable=False,server_default="synthetic"),sa.Column("connection",sa.Text(),nullable=False,server_default=""),sa.Column("enabled",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("simulated",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("scenario",sa.String(32),nullable=False,server_default="normal"),sa.Column("processing_fps",sa.Integer(),nullable=False,server_default="2"),sa.Column("resize_limit",sa.Integer(),nullable=False,server_default="1280"),sa.Column("timeout_seconds",sa.Integer(),nullable=False,server_default="5"),sa.Column("reconnect_min_seconds",sa.Integer(),nullable=False,server_default="1"),sa.Column("reconnect_max_seconds",sa.Integer(),nullable=False,server_default="30"),sa.Column("status",sa.String(24),nullable=False,server_default="OFFLINE"),sa.Column("error_category",sa.String(48),nullable=False,server_default=""),sa.Column("last_frame",sa.DateTime(timezone=True)),sa.Column("reconnects",sa.Integer(),nullable=False,server_default="0"),sa.Column("processed",sa.Integer(),nullable=False,server_default="0"),sa.Column("dropped",sa.Integer(),nullable=False,server_default="0"),sa.Column("secret",sa.Text(),nullable=False,server_default=""))
    op.create_table("rules",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("camera_id",sa.Integer(),sa.ForeignKey("cameras.id"),nullable=False),sa.Column("event_type",sa.String(32),nullable=False),sa.Column("enabled",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("min_duration",sa.Integer(),nullable=False,server_default="2"),sa.Column("cooldown",sa.Integer(),nullable=False,server_default="30"),sa.Column("zone",sa.JSON(),nullable=False),sa.Column("config",sa.JSON(),nullable=False))
    op.create_table("incidents",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("camera_id",sa.Integer(),sa.ForeignKey("cameras.id"),nullable=False),sa.Column("rule_id",sa.Integer(),sa.ForeignKey("rules.id"),nullable=False),sa.Column("event_type",sa.String(32),nullable=False),sa.Column("status",incident_status,nullable=False,server_default="NEW"),sa.Column("severity",sa.String(16),nullable=False,server_default="HIGH"),sa.Column("simulated",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("first_seen",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("last_seen",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("snapshot",sa.String(160),nullable=False),sa.Column("metadata_json",sa.JSON(),nullable=False),sa.Column("config_snapshot",sa.JSON(),nullable=False),sa.Column("evidence_expired",sa.Boolean(),nullable=False,server_default=sa.false()))
    op.create_table("transitions",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("incident_id",sa.Integer(),sa.ForeignKey("incidents.id"),nullable=False),sa.Column("actor_id",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("from_status",sa.String(20),nullable=False),sa.Column("to_status",sa.String(20),nullable=False),sa.Column("note",sa.String(500),nullable=False,server_default=""),sa.Column("at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()))
    op.create_table("notifications",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("incident_id",sa.Integer(),sa.ForeignKey("incidents.id"),nullable=False),sa.Column("kind",sa.String(32),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("read",sa.Boolean(),nullable=False,server_default=sa.false()))
    op.create_table("worker_lease",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("owner",sa.String(80),nullable=False),sa.Column("expires",sa.DateTime(timezone=True),nullable=False))
def downgrade():
    op.drop_table("worker_lease");op.drop_table("notifications");op.drop_table("transitions");op.drop_table("incidents");op.drop_table("rules");op.drop_table("cameras");op.drop_table("users")
